---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: github-instavote
  namespace: instavote
spec:
  address: https://github.com/devops-0001/instavote-deploy
  secretRef:
    name: github-token
  type: github
