---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  interval: 1h
  ref:
    branch: main
  secretRef:
    name: github-instavote
  url: https://github.com/devops-0001/instavote-deploy.git
